var liandong = [
    { name: '桔梗', imgSrc: '319.png' },
    { name: '杀生丸', imgSrc: '314.png' },
    { name: '犬夜叉', imgSrc: '313.png' },
    { name: '蜜桃&芥子', imgSrc: '310.png' },
    { name: '阿香', imgSrc: '309.png' },
    { name: '鬼灯', imgSrc: '308.png' },
    { name: '卖药郎', imgSrc: '305.png' },
    { name: '奴良陆生', imgSrc: '294.png' }
  ];

var sp = [
    { name: '苍风一目连', imgSrc: '327.png' },
    { name: '稻荷神御馔津', imgSrc: '326.png' },
    { name: '炼狱茨木童子', imgSrc: '322.png' },
    { name: '少羽大天狗', imgSrc: '315.png' }
  ];
var ssr =  [
    { name: '八岐大蛇' , imgSrc: '325.png' },
    { name: '白藏主' , imgSrc: '316.png' },
    { name: '鬼切' , imgSrc: '312.png' },
    { name: '面灵气' , imgSrc: '311.png' },
    { name: '山风' , imgSrc: '296.png' },
    { name: '御馔津' , imgSrc: '304.png' },
    { name: '玉藻前' , imgSrc: '300.png' },
    { name: '雪童子' , imgSrc: '292.png' },
    { name: '彼岸花' , imgSrc: '288.png' },
    { name: '荒' , imgSrc: '283.png' },
    { name: '花鸟卷' , imgSrc: '279.png' },
    { name: '辉夜姬' , imgSrc: '280.png' },
    { name: '大天狗' , imgSrc: '217.png' },
    { name: '酒吞童子' , imgSrc: '219.png' },
    { name: '荒川之主' , imgSrc: '248.png' },
    { name: '阎魔' , imgSrc: '255.png' },
    { name: '两面佛' , imgSrc: '258.png' },
    { name: '小鹿男' , imgSrc: '259.png' },
    { name: '茨木童子' , imgSrc: '265.png' },
    { name: '青行灯' , imgSrc: '266.png' },
    { name: '妖刀姬' , imgSrc: '269.png' },
    { name: '一目连' , imgSrc: '272.png' }
]

var sr = [
    { name: '化鲸' , imgSrc: '324.png' },
    { name: '一反木绵' , imgSrc: '320.png' },
    { name: '入殓师' , imgSrc: '321.png' },
    { name: '於菊虫' , imgSrc: '318.png' },
    { name: '人面树' , imgSrc: '317.png' },
    { name: '猫掌柜' , imgSrc: '307.png' },
    { name: '薰' , imgSrc: '298.png' },
    { name: '弈' , imgSrc: '303.png' },
    { name: '日和坊' , imgSrc: '297.png' },
    { name: '追月神' , imgSrc: '295.png' },
    { name: '百目鬼' , imgSrc: '293.png' },
    { name: '书翁' , imgSrc: '291.png' },
    { name: '小松丸' , imgSrc: '290.png' },
    { name: '匣中少女' , imgSrc: '287.png' },
    { name: '鸩' , imgSrc: '285.png' },
    { name: '以津真天' , imgSrc: '286.png' },
    { name: '金鱼姬' , imgSrc: '282.png' },
    { name: '万年竹' , imgSrc: '275.png' },
    { name: '青坊主' , imgSrc: '273.png' },
    { name: '夜叉' , imgSrc: '276.png' },
    { name: '黑童子' , imgSrc: '277.png' },
    { name: '白童子' , imgSrc: '278.png' },
    { name: '烟烟罗' , imgSrc: '281.png' },
    { name: '桃花妖' , imgSrc: '200.png' },
    { name: '雪女' , imgSrc: '201.png' },
    { name: '鬼使白' , imgSrc: '210.png' },
    { name: '鬼使黑' , imgSrc: '211.png' },
    { name: '孟婆' , imgSrc: '215.png' },
    { name: '犬神' , imgSrc: '220.png' },
    { name: '骨女' , imgSrc: '223.png' },
    { name: '鬼女红叶' , imgSrc: '231.png' },
    { name: '跳跳哥哥' , imgSrc: '233.png' },
    { name: '傀儡师' , imgSrc: '242.png' },
    { name: '海坊主' , imgSrc: '247.png' },
    { name: '判官' , imgSrc: '251.png' },
    { name: '凤凰火' , imgSrc: '252.png' },
    { name: '吸血姬' , imgSrc: '253.png' },
    { name: '妖狐' , imgSrc: '254.png' },
    { name: '妖琴师' , imgSrc: '256.png' },
    { name: '食梦貘' , imgSrc: '257.png' },
    { name: '清姬' , imgSrc: '260.png' },
    { name: '镰鼬' , imgSrc: '261.png' },
    { name: '姑获鸟' , imgSrc: '262.png' },
    { name: '二口女' , imgSrc: '263.png' },
    { name: '白狼' , imgSrc: '264.png' },
    { name: '樱花妖' , imgSrc: '267.png' },
    { name: '惠比寿' , imgSrc: '268.png' },
    { name: '络新妇' , imgSrc: '270.png' },
    { name: '般若' , imgSrc: '271.png' }
]

var r = [
  { name: '天井下' , imgSrc: '323.png' },
  { name: '虫师' , imgSrc: '306.png' },
  { name: '小袖之手' , imgSrc: '302.png' },
  { name: '数珠' , imgSrc: '301.png' },
  { name: '兔丸' , imgSrc: '289.png' },
  { name: '古笼火' , imgSrc: '274.png' },
  { name: '三尾狐' , imgSrc: '202.png' },
  { name: '座敷童子' , imgSrc: '205.png' },
  { name: '鲤鱼精' , imgSrc: '206.png' },
  { name: '九命猫' , imgSrc: '207.png' },
  { name: '狸猫' , imgSrc: '208.png' },
  { name: '河童' , imgSrc: '209.png' },
  { name: '童男' , imgSrc: '212.png' },
  { name: '童女' , imgSrc: '213.png' },
  { name: '饿鬼' , imgSrc: '214.png' },
  { name: '巫蛊师' , imgSrc: '216.png' },
  { name: '鸦天狗' , imgSrc: '218.png' },
  { name: '食发鬼' , imgSrc: '221.png' },
  { name: '武士之灵' , imgSrc: '222.png' },
  { name: '雨女' , imgSrc: '224.png' },
  { name: '跳跳弟弟' , imgSrc: '225.png' },
  { name: '跳跳妹妹' , imgSrc: '226.png' },
  { name: '兵俑' , imgSrc: '227.png' },
  { name: '丑时之女' , imgSrc: '228.png' },
  { name: '独眼小僧' , imgSrc: '230.png' },
  { name: '铁鼠' , imgSrc: '232.png' },
  { name: '椒图' , imgSrc: '234.png' },
  { name: '管狐' , imgSrc: '236.png' },
  { name: '山兔' , imgSrc: '237.png' },
  { name: '萤草' , imgSrc: '238.png' },
  { name: '蝴蝶精' , imgSrc: '241.png' },
  { name: '山童' , imgSrc: '243.png' },
  { name: '首无' , imgSrc: '244.png' },
  { name: '觉' , imgSrc: '249.png' },
  { name: '青蛙瓷器' , imgSrc: '250.png' }
]

var n = [
  { name: '灯笼鬼' , imgSrc: '203.png' },
  { name: '提灯小僧' , imgSrc: '245.png' },
  { name: '赤舌' , imgSrc: '246.png' },
  { name: '盗墓小鬼' , imgSrc: '400.png' },
  { name: '寄生魂' , imgSrc: '401.png' },
  { name: '唐纸伞妖' , imgSrc: '403.png' },
  { name: '天邪鬼绿' , imgSrc: '404.png' },
  { name: '天邪鬼赤' , imgSrc: '405.png' },
  { name: '天邪鬼黄' , imgSrc: '406.png' },
  { name: '天邪鬼青' , imgSrc: '407.png' },
  { name: '帚神' , imgSrc: '408.png' },
  { name: '涂壁' , imgSrc: '409.png' }
]

var guatai = [
  { name: '彼岸花呱' , imgSrc: '427' },
  { name: '荒呱' , imgSrc: '426' },
  { name: '辉夜姬呱' , imgSrc: '425' },
  { name: '花鸟卷呱' , imgSrc: '424' },
  { name: '一目连呱' , imgSrc: '423' },
  { name: '妖刀姬呱' , imgSrc: '422' },
  { name: '青行灯呱' , imgSrc: '421' },
  { name: '茨木呱' , imgSrc: '420' },
  { name: '小鹿男呱' , imgSrc: '419' },
  { name: '两面佛呱' , imgSrc: '418' },
  { name: '阎魔呱' , imgSrc: '417' },
  { name: '荒川呱' , imgSrc: '416' },
  { name: '酒吞呱' , imgSrc: '415' },
  { name: '大天狗呱' , imgSrc: '414' }
]

var all_heros = [
  
]